services:
  sqlserver-db1:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-comparison-sqlserver1
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver1_data:/var/opt/mssql
      - ./init-scripts/sqlserver1:/docker-entrypoint-initdb.d
    networks:
      - db-network

  sqlserver-db2:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-comparison-sqlserver2
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_PID: Express
    ports:
      - "1434:1433"
    volumes:
      - sqlserver2_data:/var/opt/mssql
      - ./init-scripts/sqlserver2:/docker-entrypoint-initdb.d
    networks:
      - db-network

volumes:
  sqlserver1_data:
  sqlserver2_data:

networks:
  db-network:
    driver: bridge
