services:
  mysql-db:
    image: mysql:8.0
    container_name: sql-comparison-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb1
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts/mysql:/docker-entrypoint-initdb.d
    networks:
      - db-network

  postgres-db:
    image: postgres:15
    container_name: sql-comparison-postgres
    environment:
      POSTGRES_DB: testdb2
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/postgres:/docker-entrypoint-initdb.d
    networks:
      - db-network

volumes:
  mysql_data:
  postgres_data:

networks:
  db-network:
    driver: bridge
